### ISSUE TITLE
.gitignore missing

### ISSUE THREAD

**Issue by impredicative** [Coderx7/SimpleNet_Pytorch#1]
Please add a standard Python `.gitignore` file, e.g. [this](https://github.com/github/gitignore/blob/master/Python.gitignore). The `__pycache__` directory can then also be untracked.

**Comment by Coderx7** [comment]
@impredicative Thank you very much. I just added a new .gitignore file just as you mentioned.
I'm a newbie in Python so if I need to remove the pycache directory as well, please say so.

**Comment by impredicative** [comment]
Yes, it would have to untracked and thereby removed from the repo. This is more of a git exercise.

**Comment by Coderx7** [comment]
Thank you very much for the heads up. I really appreciate it :)
