### ISSUE TITLE
Ident bug

### ISSUE THREAD

**Issue by rlan** [Coderx7/SimpleNet_Pytorch#4]
https://github.com/Coderx7/SimpleNet_Pytorch/blob/60c2abfbae156dc704fdc118d2ea9f61c5066e61/models/simplenet.py#L147

It seems to me the return line should be executed after the for-loop above it is finished. At the current indent, it is inside the for-loop, which skips Xavier initializations.

**Comment by Coderx7** [comment]
Thank you very much. its fixed now
