### ISSUE TITLE
Redudant MaxPool layer after 10th Conv

### ISSUE THREAD

**Issue by darusik** [Coderx7/SimpleNet_Pytorch#5]
In the paper and in the Caffee implementation there is no MaxPool layer after the 10th convolution layer, whereas it is present in the Pytorch implementation. It seems to be redundant. 

https://github.com/Coderx7/SimpleNet_Pytorch/blob/5d13ddbba6ae531ced26469c6b0f0ec18665d5ec/models/simplenet.py#L119

**Comment by Coderx7** [comment]
Thanks for pointing that out, I'll update this as soon as my time permits (I'll keep this open until the changes are merged).
